### ISSUE TITLE
After 1st use. Some Aliases that I found that may have issues

### ISSUE THREAD

**Issue by Ryzant** [ronh3/poopDeck#18]
I used the sailing portion and below 4 are what I found.

Aliases:
1. All Stop - No coding in the alias
 
![All Stop Alias](https://github.com/ronh3/poopDeck/assets/163097304/f68a4070-eda6-454c-9189-42717ae1d867)

 
2. Maintain - No coding in the alias
![Maintain Alias](https://github.com/ronh3/poopDeck/assets/163097304/474f4077-12fe-48e0-abc7-51c1e3efb549)

3. Turn Ship -  works but I'm saying the letter instead of whole work. E.g "Bring her to the e!" instead of "Bring her to the East!"
![Turn ship Alias](https://github.com/ronh3/poopDeck/assets/163097304/5db9a016-f287-4e86-be33-5a8dcbdbe7cc)
 
4. Set Speed - when using sssfull (or sss full), I am saying "Fullsails!". It is not working becuae it needs space between full and sails. This is same for sssfurl|relax|furl (and sss furl|relax|furl) .  sss and number (eg sss 100 or sss 0 and everything inbetween) works fine.
![Set Speed Alias](https://github.com/ronh3/poopDeck/assets/163097304/08d8e6c4-fe12-4dea-bdc6-9934807f8dd5)

Nice to have:
Douse sail - May need a douse sail for when sails are on fire
Ship Repair None - For when you want to stop ship repairs so you can raise anchor
Windboost - very very low priority. Alias for Invoke Windboost- I use this quite often and have my own alias but would be nice to have here.

Thank you for creating this.

**Comment by ronh3** [comment]
1. Fixed.
2. Fixed.
3. Fixed.
4. Fixed.
5. Douse - Added
6. Repair None - Added
7. Windboost - Added.
