### ISSUE TITLE
1st experience with Seamonsters portion.

### ISSUE THREAD

**Issue by Ryzant** [ronh3/poopDeck#20]
So just used the seamonster section of the package for the first time.

1. Manual Commnads - Fire Weapon alias is mssing fire onager chainshot. - it's the only ammo type missing. 

2. Can we include somewhere in the autofire to disable "Ship Moved Let's Try Again" Trigger? When I was using the auto fire for onager and in range of seamonster, the "Ship Moved Lets Try Again" trigger kept triggering everytime the ship moved thus interupting the shot and re-aiming. This could be my fault. Maybe "Ship Moved Lets Try Again" trigger was disabled by default and I enabled it thinking that it needed it be enabled.

3. Finally, I think it would be nice to include "SHIP REPAIR ALL" when we fire weapons. I see we already have MAINTAIN HULL before loading the weapons. If we can include SHIP REPAIR ALL there as well just so the crew is also repairing the ship.  This should save  endurance.

My faviorite is the shot counter.  Prior to using poopDeck, I was just firing and hoping the seamonser will die soon. With the shot counter, I can see a finish line to when the monster dies.

Once again appreciate you creating poopDeck!

**Comment by Ryzant** [comment]
2.)  This is reagarding #2 from original issue post. Just took a peak at the Seamonster Functions saw there is a function poopDeck.SeaFiring already made for this. However there doesnt seem to be a trigger firing the function when we aim a weapon.


This next one is not really coding related so might be off topic.  I noticed the timer was part of  when the monster surfaced.  Does the moster respawn in game start when the monster surfaces or when it was defeated? I was told monster respawns 15 after defeated by one person before and another person told me 10 minutes after defeated.  Just wondering on respawn since I haven't been seamonster hunting long.

**Comment by ronh3** [comment]
1) Whoops! Will fix.

2) Auto firing is definitely broken at the moment. Experienced it the last time I took the ship out and tried it out. Need to diagram my logic for it, ensure I've the proper triggers/scripts/etc. made, and then make it actually work :)

3) My understanding was that only the captain is able to have the crew repair. Will investigate, and if this isn't the case, add it in.

As for respawn, I was told it was twenty minutes from when it surfaces. Thus far, that's been correct in my experience more so than from the time it was killed.

**Comment by Ryzant** [comment]
3. You're correct. It seems only the Captain (or crew with Captain perms) in the quarterdeck or melded to the figurehead is able to have the crew repair via ship repair commands.

**Comment by ronh3** [comment]
1) Added. Alias is firc
2) Appear to have fixed autofiring. For the time being, so long as you're in range of the seamonster, it will continue firing. Once you go out of range, it'll attempt to fire when the ship moves. Once it does start firing, it should stop attempting and disable that trigger. When your shot is interrupted, it'll just pop a message and take no further action.

Currently working on in-place updates. That's been a touch slower to figure out than I would've liked :)

Any other features you'd like to see implemented?
